name: 'Bash PageSpeed Insights Check'
description: 'Check against PageSpeed Insights using bash'
inputs:
  url:
    description: 'The URL to check'
    required: true
  score:
    description: 'The minimum score desired'
    required: false
    default: 90
  device-type:
    description: 'Device type used for the run (desktop/mobile)'
    required: true
    default: 'desktop'
runs:
  using: 'composite'
  steps:
    - name: 'Check PSI score'
      run: ${{ github.action_path }}/check-score.sh ${{ inputs.url }} ${{ inputs.device-type }} ${{ inputs.score }}
      shell: bash
